spring:
  # ??? ?? ??
  h2.console:.enabled: true

  jpa:
    properties:
      # ??? ? ?? ?? ?? ?? ??? ?? ??.
      hibernate.format_sql: true
    # ddl ??
    hibernate:.ddl-auto: create-drop
    # ??? ?? ?? ??.
    show-sql: true

  datasource:
    url: jdbc:h2:mem:test_mem
    username: iksad
    password: 1234

logging:
  level:
    # ??? ??? ????? ????.
    org.hibernate.type: trace